### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by xxholyChalicexx** [RonMelkhior/Coinpayments-IPN#7]
i get this error:
Fatal error: Class 'RonMelkhior\CoinpaymentsIPN\IPN' not found in /home/ubuntu/workspace/hello.php on line 5 Call Stack: 0.0010 235288 1.

**Comment by RonMelkhior** [comment]
Hi!

Did you add it via Composer and then import the vendor autoload?

**Comment by xxholyChalicexx** [comment]
yes what i did is.......install via composer....a folder called "vendor" got downloaded.....then i created a file hello.php on a level where that vendor folder was present.

**Comment by xxholyChalicexx** [comment]
![screenshot from 2018-05-24 23-42-25](https://user-images.githubusercontent.com/20463819/40503592-37f5ea1a-5fac-11e8-83cb-a623283b3ba3.png)

**Comment by xxholyChalicexx** [comment]
and that page.php is where i am writing the code:
`<?php

use CoinpaymentsIPN\IPN;

$ipn = new IPN();
$ipn->setMerchantID('9636bba872a84ce80d4d29f9628cec78')
    ->setIPNSecret('hello');

try {
    if ($ipn->validate($_POST, $_SERVER)) {
        // Payment was successful, verify vars such as the transaction ID/email and process it.
    } else {
        // IPN worked, but the payment is pending.
    }
} catch (RonMelkhior\CoinpaymentsIPN\Exceptions\InvalidRequestException $e) {
    // The IPN data was not valid to begin with (missing data, invalid IPN method).
} catch (RonMelkhior\CoinpaymentsIPN\Exceptions\InsufficientDataException $e) {
    // Sufficient data provided, but either the merchant ID or the IPN secret didn't match.
} catch (RonMelkhior\CoinpaymentsIPN\Exceptions\FailedPaymentException $e) {
    // IPN worked, but the payment has failed (PayPal refund/cancelled/timed out).
}

?>`

**Comment by RonMelkhior** [comment]
You have to import `vendor/autoload.php`.

Like so:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// ... rest of the code.
```

**Comment by xxholyChalicexx** [comment]
well still not working says no such file or directory as vendor/autoload...... may be i might have done some mistake...... will try again and will let you know. And thank you so much for reaching out. Really appreciate it

**Comment by xxholyChalicexx** [comment]
well it worked it seems.....dont see any error........one last question.....suppose i want to copy it into another server......just copy pasting the files(vendor,composer.json,composer.lock)....will it still work ?

**Comment by RonMelkhior** [comment]
Yes.

Optimally, you'd add `vendor/` to `.gitignore`, and then install Composer in production and install it that way. You can have it automatically executed if you deploy it from something like a Git repo.  
That way you get to enjoy some of the goodies like `dumpautoload` and not having to copy thousands of files.

Feel free to read https://getcomposer.org/doc/01-basic-usage.md
